### ISSUE TITLE
Duplicate class found

### ISSUE THREAD

**Issue by hysapp** [mapbox/mapbox-search-android#111]
When I use the map with the search engine:

   `implementation 'com.mapbox.maps:android:10.4.2'`
   `implementation 'com.mapbox.search:mapbox-search-android:1.0.0-beta.41'`

I get a `Duplicate class found` error when building the project:

`Duplicate class com.mapbox.android.core.location.LocationEngine found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.location.LocationEngineCallback found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.location.LocationEngineProvider found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.location.LocationEngineRequest found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.location.LocationEngineRequest$Builder found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.location.LocationEngineResult found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.permissions.PermissionsListener found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.permissions.PermissionsManager found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
Duplicate class com.mapbox.android.core.permissions.PermissionsManager$AccuracyAuthorization found in modules jetified-common-23.2.0-rc.3-runtime (com.mapbox.common:common:23.2.0-rc.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
`

**Comment by ghadeeraqraa1992** [comment]
I have the same issue

**Comment by kalbaxa** [comment]
Thanks for reaching out. Please update to the latest SDK version, this should be resolved as version compatibility:
https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.42

**Comment by DzmitryFomchyn** [comment]
Hey @hysapp, @ghadeeraqraa1992,
It seems that this is a duplicated issue https://github.com/mapbox/mapbox-search-android/issues/108

The Search SDK 1.0.0-beta.41 is incompatible with the Maps SDK 10.4.2. You can find compatible versions of Search/Maps/Nav SDK using the instruction here https://docs.mapbox.com/android/search/guides/install/#add-the-dependency

Also, note that you need to remove any explicit dependency declaration to `com.mapbox.mapboxsdk:mapbox-android-core:<version>` (if you have any) from the project to avoid duplicated class as described here https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.41.

I'll close this issue for now. Please feel free to reopen it if you still have a similar error.
