### ISSUE TITLE
MapBox Search panel like on IOS

### ISSUE THREAD

**Issue by WiedmololFool** [mapbox/mapbox-search-android#130]
Is it possible to add IOS-like panel with current sdk for android?

![image](https://user-images.githubusercontent.com/95405285/217223986-25c0010c-ead6-4a76-9a5a-a874b7c197da.png)

**Comment by DzmitryFomchyn** [comment]
Unfortunately, no. As for now we don't have such plans.

This view was part of the SDK before but we decided to remove it as it was too complex, hard to customise for different use cases, hard to support and wasn't used by customers at that time.

I encourage you to try UI components that the SDK provides now https://docs.mapbox.com/android/search/guides/search-ui/, I hope you'll find them useful.

The view you are asking about was removed in the [1.0.0-beta.33](https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.33). As an option you can checkout [1.0.0-beta.32](https://github.com/mapbox/mapbox-search-android/tree/v1.0.0-beta.32) and copy removed views to your code.

I'll close the issue for now. Feel free to reopen it if you have more questions.
