### ISSUE TITLE
Should be compatible to integrate with Modern UI (JetPack Compose) 

### ISSUE THREAD

**Issue by jk2pr** [mapbox/mapbox-search-android#135]
We are expecting it to be compatible with Jetpack compose

**Comment by DzmitryFomchyn** [comment]
Unfortunately, it's not in the nearest plans yet. [Contrubuting](https://github.com/mapbox/mapbox-search-android#contributing) is welcomed, so feel free to open PRs!

**Comment by DzmitryFomchyn** [comment]
I'll close this issue for now. Watch Search SDK releases to be notified of new features.
