### ISSUE TITLE
Your app uses https://api.mapbox.com/geocoding/v5 to get recommendations after using AddressAutofill, somehow after integrating your modules in my project it uses https://api.mapbox.com/autofill because of that I can't get recommendations to search

### ISSUE THREAD

**Issue by AndrewKisyk** [mapbox/mapbox-search-android#141]
## Environment

- Search SDK Component I use .aar files built from your modules without any changes
- Android OS version: 13
- Devices affected: pixel
- Search SDK Version: 0.67.1
- Included in project Maps SDK, Nav SDK versions if available: MapBox-10.10.0 Navigation-2.11.0

## Code examples
<!--- 

Include code with 
  - SDK initialization
  - Search requests
  - Search options (proximity point, countries, languages, etc.)
  - Code snippets that cause crash
  - etc. 

private val addressAutofill = AddressAutofill.create(MAPBOX_API_KEY)
 addressAutofill.suggestions(Query.create(text) ?: return Result.Error(
            Exception()
 ), AddressAutofillOptions()).toResult()

**Comment by DzmitryFomchyn** [comment]
@AndrewKisyk could you please give more details and code examples?

**Comment by AndrewKisyk** [comment]
@DzmitryFomchyn in "sample" app from this repo, after calling ` addressAutofill.suggestions(query = query, options = AddressAutofillOptions())` this( "[ https://api.mapbox.com/geocoding]" search endpoint called. When I use this method from my app  this( "[ https://api.mapbox.com/autofill]" search endpoint called. How should I configure AddressAutofill to use the same endpoint as yours?

**Comment by DzmitryFomchyn** [comment]
@AndrewKisyk ,

> in "sample" app from this repo, after calling  addressAutofill.suggestions(query = query, options = AddressAutofillOptions()) this( "[ https://api.mapbox.com/geocoding]" search endpoint called

It shouldn't work this way, `AddressAutofill` works over `https://api.mapbox.com/autofill` endpoint. You can check it in the following code example

```
class AddressAutofillKotlinExampleActivity : AppCompatActivity() {

    private lateinit var addressAutofill: AddressAutofill

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        HttpServiceFactory.getInstance().setInterceptor(object : HttpServiceInterceptorInterface {
            override fun onRequest(request: HttpRequest): HttpRequest {
                Log.i("SearchApiExample", "onRequest: $request")
                return request
            }

            override fun onDownload(download: DownloadOptions): DownloadOptions {
                Log.i("SearchApiExample", "onDownload: $download")
                return download
            }

            override fun onResponse(response: HttpResponse): HttpResponse {
                Log.i("SearchApiExample", "onResponse: $response")
                return response
            }
        })

        addressAutofill = AddressAutofill.create(
            accessToken = getString(R.string.mapbox_access_token),
        )

        lifecycleScope.launchWhenCreated {
            val query = Query.create("740 15th St NW, Washington") ?: return@launchWhenCreated

            addressAutofill.suggestions(
                query = query,
                options = AddressAutofillOptions()
            ).onValue { suggestions ->
                Log.i("SearchApiExample", "Autofill suggestions: $suggestions")
            }.onError { error ->
                Log.i("SearchApiExample", "Autofill suggestions error", error)
            }
        }
    }
}
```

If you see that it works over `https://api.mapbox.com/geocoding`, it's a bug and I'll appreciate more details about your environment and isolated code example that could demonstrate this behavior.

If you need `https://api.mapbox.com/geocoding`, you should use [SearchEngine](https://docs.mapbox.com/android/search/guides/search-engine/#integration) with `ApiType.GEOCODING`

**Comment by DzmitryFomchyn** [comment]
@AndrewKisyk,
Any update here? Did you have a chance to check sample?

**Comment by AndrewKisykP** [comment]
@DzmitryFomchyn Yes I have. The solution is to use SearchEngine, thanks. Is it possible for me to join Beta Porgram? 
Because most of the search features are not available for me?

**Comment by DzmitryFomchyn** [comment]
@AndrewKisyk please, contact sales team for this question https://www.mapbox.com/contact/sales/.
If everything is working on the SDK side, can we close this issue?

**Comment by AndrewKisykP** [comment]
yes, sure
