### ISSUE TITLE
Can I help provide data for my city to the search database? / Могу ли я помочь предоставить данные по моему городу в базу данных поиска?

### ISSUE THREAD

**Issue by Freeze35** [mapbox/mapbox-search-android#15]
**Good afternoon, I am developing an application in the city of Ulan-Ude, can I help with providing data to the search system in my city?** /
***Добрый день я разрабатываю приложение в городе Улан-Удэ могу ли я помочь с предоставление данных в систему поиска по моему городу?***

> **Unfortunately for my city, there are practically no bindings for the coordinates of both streets and certain places.** /
*К несчастью для моего города практически нет привязок координат как улиц так и определённых мест.*

But in the application you can Mapbox Maps SDK, the names of some places in the city and streets are perfectly visible. / 
*Но в приложении можно Mapbox Maps SDK прекрасно видны наименования некоторых мест города и улиц.*

Can I help to provide street data and its end, or house data (Street , House (Latitude,Longitude) ) ? / 
*Могу помочь предоставить данные улиц и их конец, или данные домов (Улица , Дом (Latitude,Longitude) )* ?

**I will also need to know the best language to provide information** / 
***Мне также потребуется, узнать на каком языке лучше предоставлять информацию***

With Mapbox SDK just started working
The application is very well developed and ready to help if possible. / 
*C Mapbox SDK начал работать совсем недавно*
*Приложение очень хорошо развивается готов помочь если возможно.*

Thank you, I hope for a speedy reply. / *Спасибо, надеюсь на скорый ответ.*

**Comment by DzmitryFomchyn** [comment]
Hey @Freeze35,
Thank you very much for your willingness to contribute!

Simply speaking, they're three sources of data for SDK's search engine:
1. Backend
2. Offline data
3. Data providers

At the moment we don't accept external data for backend and offline as a dataset and without validation. You can submit single addresses via https://www.mapbox.com/contribute/#/add/address but we cannot guarantee when they appear in the dataset.

But you can use your local data in your application by adding it to a data provider. This data won't be available globally, only inside your application. You can read more about data providers here https://docs.mapbox.com/android/search/guides/data-providers/

**Comment by Freeze35** [comment]
Thanks for the description. I hope to give you as much data as I can. I will also temporarily add my data lists to my app.. I close this topic.
