### ISSUE TITLE
Failed to build when using 11.0.0 and MapBox Search 1.0.0-rc7

### ISSUE THREAD

**Issue by PavlosTze** [mapbox/mapbox-search-android#171]
## Environment

- Android OS version:
- Devices affected: -
- Maps SDK Version: 11.0.0
- MapBox Search Version: 1.0.0-rc7

## Observed behavior and steps to reproduce
I am importing both libraries:
```
    implementation("com.mapbox.maps:android:11.0.0")
    implementation("com.mapbox.search:mapbox-search-android:1.0.0-rc.7")
```
And I get the following error:

> * What went wrong:
> Execution failed for task ':app:checkRemoteProdDebugDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class com.mapbox.common.module.okhttp.CallbackWrapper found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.CallbackWrapper$RequestCallback found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.HttpCallback found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.IdGenerator found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.LazyClient found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.MapboxOkHttpService found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.MapboxOkHttpService$1 found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.MapboxOkHttpService$HttpServiceOfflineSwitchObserver found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.NetworkUsageListener found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.NetworkUsageListener$1 found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.NetworkUsageListener$DummyEventListener found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.common.module.okhttp.NetworkUsageListener$NetworkUsageMetricCallback found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)
>      Duplicate class com.mapbox.module.Mapbox_HttpClientModuleConfiguration found in modules common-24.0.0-runtime (com.mapbox.common:common:24.0.0) and okhttp-23.6.0-runtime (com.mapbox.common:okhttp:23.6.0)

When commenting out the search library it builds successfully with no error.
## Expected behavior

I would expect it to build with no issues.

**Comment by TiagoLira** [comment]
I've had this issue in the past, whenever the two libraries use different versions of the com.mapbox.common library.
Is there a gradle workaround that is safe, or do we need to wait for a search library update?

Right now this is forcing me to use a maps version that is 6 months old.

**Comment by PavlosTze** [comment]
@eugenes78 Do we have any news on that?

**Comment by PavlosTze** [comment]
This is still an issue on Mapbox 11.1.0, we cannot upgrade Mapbox library. Any news on that @eugenes78 @DzmitryFomchyn ?

**Comment by jvanderwee** [comment]
Ditto. We'd love to start using Maps v11!

**Comment by narko** [comment]
For the records, this issue also affects [Mapbox Navigation 2.18.0](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.18.0)

**Comment by narko** [comment]
I spotted the following on the navigation lib: https://docs.mapbox.com/android/navigation/build-with-coreframework/migration-from-v2#maps-sdk

Are we expecting the same change for the search lib in `2.0.0-alpha`?

**Comment by eugenes78** [comment]
[2.0.0-beta.4](https://github.com/mapbox/mapbox-search-android/releases/tag/v2.0.0-beta.4) works with Maps v11. Please let me know if you hit any issues.

**Comment by dudeuter** [comment]
For anyone looking at this in the future...

Maps, Navigation, and Search rely on a common shared object. Your best bet is to find a version of the SDKs that you use that have a shared common version; this is done for you in the case that you're importing your Maps SDK as a dependency of the Navigation or Search SDKs.

If you're explicitly overriding the Maps SDK; or trying to use Search and Navigation together you'll need to watch out for this. We usually publish the Common SDK version in the release notes, [example](https://github.com/mapbox/mapbox-search-android/releases#:~:text=Native%20SDK%200.71.0-,Common%20SDK%2023.6.0,-Kotlin%201.5.31)

But you can also find them in the repo's source code:

https://github.com/mapbox/mapbox-search-android/blob/720aef6b8c33b87d7f1c4bdf7df3c15d95a28e39/MapboxSearch/gradle/versions.gradle#L45

[v10 Maps SDK](https://github.com/mapbox/mapbox-maps-android/blob/3af61b38df6e340d7a19a769cf8f09a1d940683f/buildSrc/src/main/kotlin/Project.kt#L118)

[v11 Maps SDK](https://github.com/mapbox/mapbox-maps-android/blob/286baa18092632f6216c6ce95053f6be2e51b9b0/gradle/libs.versions.toml#L39)

[v2 Navigation SDK](https://github.com/mapbox/mapbox-navigation-android/blob/5ae766d7ed949ece7fa5b91b7c5de36b6f48ca10/gradle/dependencies.gradle#L28)

**Comment by jvanderwee** [comment]
@dudeuter a Mapbox bill of materials would be nice to ensure compatible versions are used 🙏
