### ISSUE TITLE
SearchBox returns incorrect Data 

### ISSUE THREAD

**Issue by trungledangAxonActive** [mapbox/mapbox-search-android#179]
Hi Mapbox team, first of all, thank you for great Library. It's very helpful to us. 
I know this is not related to your Repo, but I could not find the repo or any resources that I can use to report to MapBox team. I posted this with the hope that you can help me reach to them and let them know about this issue. Thank you so much.

# Issue 
The data (locality in context) returns incorrect data
API: https://docs.mapbox.com/playground/search-box/?q=Comedy+Cellar&language=en&country=us&session_token=0eb14ef0-969a-46c1-88d1-b9451650e314

# Description 
We're using this API and before that it returned the data correctly, but now it doesn't. It should return `Manhattan` instead of meaningless character `d` in locality. 

![Screenshot 2024-01-18 at 15 00 48](https://github.com/mapbox/mapbox-search-ios/assets/111328770/99df4b9a-d386-41cb-88ca-35453f61d0dc)

**Comment by aokj4ck** [comment]
@trungledangAxonActive was this resolved by https://github.com/mapbox/mapbox-search-ios/issues/149#issuecomment-1909238713 or is the issue still occurring?

**Comment by trungledangAxonActive** [comment]
It was resolved on that comment. Sorry for forgetting closing this issue, I will close it as resolved now. Thanks @aokj4ck .
