### ISSUE TITLE
private fun com.mapbox.search.result.SearchAddress.isCountryWithRegions(country: String?): Boolean does not work for "United States"

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-search-android#60]
## Environment

- Android OS version: All versions
- Devices affected: All devices
- Search SDK Version: 1.0.0-beta.33
- Included in project Maps SDK, Nav SDK versions if available: Mapbox SDK 10.6.1

## Code examples

```
    private fun isCountryWithRegions(country: String?): Boolean = country?.let {
        listOf("united states of america", "usa").contains(country.lowercase(Locale.getDefault()))
    } ?: false

    fun main() {
        val result = isCountryWithRegions("United States")
        print (result) // returns false because "United States"/"united states" does not contain either "united states of america" or "usa".
    }
```

## Observed behavior and steps

Because of this, Search results with the country "United States" will not show the region with the default `FormatStyle.Medium`. E.g. "17537 Fernwood Drive, Jamestown, California" will just be "17537 Fernwood Drive, Jamestown".

## Expected behavior

The region will be included.

**Comment by DzmitryFomchyn** [comment]
Thanks for the issue, will fix it in the next SDK release!
