### ISSUE TITLE
Build fails due to duplicate class in two different MapBox modules

### ISSUE THREAD

**Issue by eeVoskos** [mapbox/mapbox-search-android#85]
## Environment

- Android OS version: 13 (any)
- Devices affected: All
- Search SDK Version: `1.0.0-beta.37`
- Included in project Maps SDK, Nav SDK versions if available: `com.mapbox.maps:android:10.8.1`

## Code examples

No code necessary, just adding both dependencies:

```
implementation "com.mapbox.maps:android:10.8.0"
implementation "com.mapbox.search:mapbox-search-android:1.0.0-beta.37"
```

## Observed behavior and steps

When adding both the above dependencies and try to compile the app, the build fails with this error:

```
Duplicate class com.mapbox.common.MapboxCommonLogger found in modules base-10.8.1-runtime (com.mapbox.maps:base:10.8.1) and common-23.1.0-beta.1-runtime (com.mapbox.common:common:23.1.0-beta.1)
```

## Expected behavior

The build should succeed.

**Comment by DzmitryFomchyn** [comment]
You need to pick Search and Maps SDK with the same `Common SDK` version. As [Search SDK 1.0.0-beta.37](https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.37) is based on the `Common SDK 23.1.0-beta.1`, you can use [Maps SDK 10.9.0-beta.1](https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.9.0-beta.1).

We'll adjust our SDK compatibility documentation, thank you!
