### ISSUE TITLE
Reverse geocoding doesn't return address number

### ISSUE THREAD

**Issue by PavlosTze** [mapbox/mapbox-search-android#88]
## Environment

- Android OS version: 12
- Devices affected: Development device
- Search SDK Version: [1.0.0-beta-37](com.mapbox.search:mapbox-search-android:1.0.0-beta.37)
- Included in project Maps SDK, Nav SDK versions if available:

## Code examples

```
    override suspend fun getAddressFromPoint(point: Point): Either<Failure, List<SearchResult>> {
        return suspendCoroutine { continuation ->
            mapBoxSearchEngine.search(
                ReverseGeoOptions(
                    center = point,
                    limit = SEARCH_LIMIT,
                    types = SEARCH_TYPES
                ),
                object : SearchCallback {
                    override fun onError(e: Exception) {
                        if (e is SearchCancellationException) {
                            Timber.d("Search was cancelled due to new point [point=$point]")
                            continuation.resumeWith(Result.success(Either.Left(CancellationError)))
                        } else {
                            Timber.w(e, "Reverse Geocoding failure [point=$point]")
                            continuation.resumeWith(
                                Result.success(Either.Left(MapBoxError.GeocodingError))
                            )
                        }
                    }

                    override fun onResults(
                        results: List<SearchResult>,
                        responseInfo: ResponseInfo
                    ) {
                        continuation.resumeWith(Result.success(Either.Right(results)))
                    }
                }
            )
        }
    }
```
## Observed behavior and steps

Running the above code for any given point, returns the address but **NOT the address' number**. Reverse Geocoding via MapBox's API returns the address number as well.

## Expected behavior

The reverse geocoding function to return the address number along with the address.

**Comment by DzmitryFomchyn** [comment]
@PavlosTze what do you mean by `address number`? House number?

Would be great to see request options you use (point, SEARCH_LIMIT, SEARCH_TYPES) and result example you'd like to see.

**Comment by DzmitryFomchyn** [comment]
@PavlosTze any updates here?

**Comment by PavlosTze** [comment]
Hello @DzmitryFomchyn , it turned out that I hadn't specified correctly the `SEARCH_TYPES`. I'm sorry for this inconvenience, therefore I am closing this issue.
